# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: pipeline-magnum
on:
  workflow_call:
jobs:
  magnum-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ENABLE_MAGNUM_SERVICE: 'true'
      TEST_TAGS: magnum
    steps:
    - uses: actions/checkout@v4.1.0
