# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: pipeline-vintrace-core
on:
  workflow_call:
jobs:
  vintrace-core-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ENABLE_MAGNUM_SERVICE: 'false'
      TEST_TAGS: vintrace & regression
    steps:
    - uses: actions/checkout@v4.1.0
